# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60091a90c86a81d40c6ed374f0db9a44e43f8cf1f5f0e9ad0b740f0b436cdfc772c19c3a88a2088d2840395b63ebb0a09ef87a13e930def614615c2422a87be8

test:
  secret_key_base: 4328d73e5b562a01cdbc5eec1b145b825ac595ff361bc918d968d3785328cecce3daa3e47fed3f57366fc18eeb62abb52c4c662bd0b2f823e2d94a2d1fdb7387

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
